/**
 * Seeded demo data for the practice-management simulator.
 *
 * Every name, address, title reference, email and dollar figure below is
 * invented for training. Nothing here is copied from the firm's live system.
 */

import type {
  SimActivity,
  SimContact,
  SimDisbursement,
  SimDocument,
  SimEmail,
  SimEvent,
  SimMatter,
  SimMemo,
  SimMessage,
  SimLead,
  SimPhoneMessage,
  SimState,
  SimWorkflow,
  SimTask,
  SimTimeEntry,
} from "./types";

/** The simulator runs on a fixed "today" so seeded dates never go stale. */
export const SIM_TODAY = "2026-08-19";

export const SIM_USER = {
  name: "Shane Capati",
  initials: "SC",
  firm: "Cremorne Conveyancing",
};

export const SIM_STAFF = ["Shane Capati", "Jennie Tonner", "Harold Galvo", "Monika Stelzner"];

export const ACTIVITY_CODES = [
  { code: "PCHS1", label: "Acting on a purchase" },
  { code: "REVIE", label: "Contract review" },
  { code: "PERUS", label: "Perusing documents" },
  { code: "TELEP", label: "Telephone attendance" },
  { code: "LETTE", label: "Letter / email out" },
  { code: "SETTL", label: "Attending settlement" },
];

/** Billing Units dropdown options. */
export const BILLING_UNITS = [
  "6 minute units",
  "10 minute units",
  "15 minute units",
  "Actual time",
];

export const BILLING_FREQUENCIES = ["On completion", "Monthly", "Fortnightly", "Weekly"];

export const REFERRAL_TYPES = [
  "Existing client",
  "Referral — real estate agent",
  "Referral — mortgage broker",
  "Referral — past client",
  "Online enquiry",
  "Walk-in",
];

export const DISBURSEMENT_CODES = [
  { code: "SEARCH", label: "Search fee" },
  { code: "PEXA", label: "PEXA fee" },
  { code: "REGO", label: "Registration fee" },
  { code: "COUNC", label: "Council certificate" },
  { code: "TITLE", label: "Title search" },
];

const matters: SimMatter[] = [
  {
    id: "m-4182",
    number: "004182",
    type: "Purchase",
    clientName: "Amara Beltran & Joel Beltran",
    clientEmail: "amara.beltran@examplemail.com",
    clientPhone: "+61 412 908 553",
    otherPartyName: "Whitlam, Trevor D. and Denise K.",
    otherPartySolicitor: "Harrowgate Legal",
    otherPartySolicitorContact: "Bianca Oyelaran",
    propertyAddress: "14 Marlowe Street, Kellyville NSW 2155",
    titleReference: "42/1104882",
    stage: "Post Exchange",
    status: "Open",
    settlementDate: "2026-09-04",
    purchasePrice: 1875000,
    depositPaid: 187500,
    feeEarnerInitials: "JT",
    assistantInitials: "SC",
    amlComplete: false,
    riskRating: "Medium",
    billing: { trustBalance: 0, unbilled: 0, unbilledIncGst: 0, unpaid: 4620.5 },
    nextStep: null,
    nextStepDate: null,
    createdAt: "2026-05-11",
  },
  {
    id: "m-4176",
    number: "004176",
    type: "Sale",
    clientName: "Priya Raghunathan",
    clientEmail: "p.raghunathan@examplemail.com",
    clientPhone: "+61 438 221 070",
    otherPartyName: "Fenwick, Callum J.",
    otherPartySolicitor: "Delacourt & Vine Conveyancing",
    otherPartySolicitorContact: "Marcus Delacourt",
    propertyAddress: "8/22 Kestrel Parade, Chatswood NSW 2067",
    titleReference: "8/SP91442",
    stage: "Pre-Settlement",
    status: "Open",
    settlementDate: "2026-08-27",
    purchasePrice: 1140000,
    depositPaid: 114000,
    feeEarnerInitials: "SC",
    assistantInitials: "SC",
    amlComplete: true,
    riskRating: "Low",
    billing: { trustBalance: 2500, unbilled: 1450, unbilledIncGst: 1595, unpaid: 0 },
    nextStep: "Book settlement in PEXA",
    nextStepDate: "2026-08-21",
    createdAt: "2026-06-02",
  },
  {
    id: "m-4190",
    number: "004190",
    type: "Purchase",
    clientName: "Nathan Okonkwo",
    clientEmail: "n.okonkwo@examplemail.com",
    clientPhone: "+61 401 774 316",
    otherPartyName: "Sandoval, Rosalie M.",
    otherPartySolicitor: "Pemberton Waye Lawyers",
    otherPartySolicitorContact: "Elise Pemberton",
    propertyAddress: "61 Barrenjoey Grove, Baulkham Hills NSW 2153",
    titleReference: "17/884213",
    stage: "Contract Review",
    status: "Open",
    settlementDate: null,
    purchasePrice: 1395000,
    depositPaid: null,
    feeEarnerInitials: "JT",
    assistantInitials: "SC",
    amlComplete: false,
    riskRating: null,
    billing: { trustBalance: 0, unbilled: 900, unbilledIncGst: 990, unpaid: 0 },
    nextStep: "Send contract review report to client",
    nextStepDate: "2026-08-20",
    createdAt: "2026-08-04",
  },
  {
    id: "m-4193",
    number: "004193",
    type: "Purchase",
    clientName: "Sofia Marchetti & Dario Marchetti",
    clientEmail: "sofia.marchetti@examplemail.com",
    clientPhone: "+61 470 553 812",
    otherPartyName: "To be advised",
    otherPartySolicitor: "Not yet nominated",
    otherPartySolicitorContact: "",
    propertyAddress: "Property not yet identified",
    titleReference: "",
    stage: "Matter Preparation",
    status: "Open",
    settlementDate: null,
    purchasePrice: null,
    depositPaid: null,
    feeEarnerInitials: "SC",
    assistantInitials: "SC",
    amlComplete: false,
    riskRating: null,
    billing: { trustBalance: 0, unbilled: 0, unbilledIncGst: 0, unpaid: 0 },
    nextStep: "Send client onboarding pack",
    nextStepDate: "2026-08-19",
    createdAt: "2026-08-17",
  },
  {
    id: "m-4168",
    number: "004168",
    type: "Transfer",
    clientName: "Estate of Gordon Hallsworth",
    clientEmail: "executor.hallsworth@examplemail.com",
    clientPhone: "+61 428 640 199",
    otherPartyName: "Hallsworth, Judith A. (surviving joint tenant)",
    otherPartySolicitor: "In-house",
    otherPartySolicitorContact: "",
    propertyAddress: "3 Wenlock Close, Castle Hill NSW 2154",
    titleReference: "5/220741",
    stage: "Post Exchange",
    status: "Open",
    settlementDate: "2026-09-18",
    purchasePrice: null,
    depositPaid: null,
    feeEarnerInitials: "HG",
    assistantInitials: "SC",
    amlComplete: true,
    riskRating: "Low",
    billing: { trustBalance: 0, unbilled: 0, unbilledIncGst: 0, unpaid: 1320 },
    nextStep: null,
    nextStepDate: null,
    createdAt: "2026-04-28",
  },
  {
    id: "m-4155",
    number: "004155",
    type: "Sale",
    clientName: "Wilhelmina Dagostino",
    clientEmail: "w.dagostino@examplemail.com",
    clientPhone: "+61 413 002 884",
    otherPartyName: "Ferreira, Bruno L. and Ana P.",
    otherPartySolicitor: "Northbrook Conveyancing",
    otherPartySolicitorContact: "Grace Northbrook",
    propertyAddress: "27 Sennen Avenue, Dulwich Hill NSW 2203",
    titleReference: "B/408117",
    stage: "Post Settlement",
    status: "Closed",
    settlementDate: "2026-08-07",
    purchasePrice: 1620000,
    depositPaid: 162000,
    feeEarnerInitials: "SC",
    assistantInitials: "SC",
    amlComplete: true,
    riskRating: "Low",
    billing: { trustBalance: 0, unbilled: 0, unbilledIncGst: 0, unpaid: 0 },
    nextStep: null,
    nextStepDate: null,
    createdAt: "2026-03-19",
  },
];

const emails: SimEmail[] = [
  {
    id: "e-1",
    matterId: "m-4182",
    direction: "Received",
    from: "bianca@harrowgatelegal.example",
    to: "Jennie Tonner",
    subject: "RE: Beltran purchase from Whitlam — 14 Marlowe Street",
    date: "2026-08-18 3:41 PM",
    body: "Hi Jennie,\n\nWe confirm our client will provide vacant possession on settlement. Please find attached the signed section 66W certificate.\n\nWe note settlement is booked for 4 September 2026. Could you confirm the incoming mortgagee once instructed?\n\nRegards,\nBianca Oyelaran\nHarrowgate Legal",
    hasAttachment: true,
  },
  {
    id: "e-2",
    matterId: "m-4182",
    direction: "Received",
    from: "amara.beltran@examplemail.com",
    to: "Shane Capati",
    subject: "Re: Post Exchange — Beltran purchase",
    date: "2026-08-17 8:22 PM",
    body: "Hi Shane,\n\nThanks for the update. Our broker at Ridgeline Finance said the loan approval letter should come through this week. I'll forward it as soon as I have it.\n\nOne question — do we need to organise building insurance before settlement or after?\n\nThanks,\nAmara",
    hasAttachment: false,
  },
  {
    id: "e-3",
    matterId: "m-4182",
    direction: "Sent",
    from: "shane@cremorneconveyancing.example",
    to: "Amara Beltran",
    subject: "Post Exchange — Beltran purchase from Whitlam",
    date: "2026-08-14 10:10 AM",
    body: "Dear Amara and Joel,\n\nContracts were exchanged on 8 August 2026 with settlement set for 4 September 2026. The cooling-off period has been waived by the section 66W certificate.\n\nNext steps on our end: ordering searches, preparing the transfer, and requesting adjustment figures.\n\nWhat we need from you: your financier's details, and confirmation of how you will fund the balance of the purchase price.\n\nKind regards,\nShane Capati",
    hasAttachment: false,
  },
  {
    id: "e-4",
    matterId: "m-4182",
    direction: "Received",
    from: "helpdesk@searchprovider.example",
    to: "Shane Capati",
    subject: "Matter: 004182 — Sewer diagram and drainage search complete",
    date: "2026-08-13 4:21 PM",
    body: "Your search order for 14 Marlowe Street, Kellyville NSW 2155 has been completed. 3 documents are attached.",
    hasAttachment: true,
  },
  {
    id: "e-5",
    matterId: "m-4176",
    direction: "Received",
    from: "marcus@delacourtvine.example",
    to: "Shane Capati",
    subject: "Raghunathan sale — settlement figures",
    date: "2026-08-18 11:05 AM",
    body: "Hi Shane,\n\nWe have received our client's bank instructions. Please send through your adjustment figures for 27 August settlement at your earliest convenience.\n\nRegards,\nMarcus Delacourt",
    hasAttachment: false,
  },
  {
    id: "e-6",
    matterId: "m-4176",
    direction: "Sent",
    from: "shane@cremorneconveyancing.example",
    to: "Priya Raghunathan",
    subject: "Settlement booked — 8/22 Kestrel Parade",
    date: "2026-08-15 9:30 AM",
    body: "Dear Priya,\n\nSettlement is booked for 27 August 2026. We will send you the final settlement statement once the purchaser's solicitor confirms adjustments.\n\nKind regards,\nShane Capati",
    hasAttachment: false,
  },
  {
    id: "e-7",
    matterId: "m-4190",
    direction: "Received",
    from: "n.okonkwo@examplemail.com",
    to: "Jennie Tonner",
    subject: "Contract review — 61 Barrenjoey Grove",
    date: "2026-08-16 6:12 PM",
    body: "Hi Jennie,\n\nAttaching the contract the agent sent me. The agent is pushing for a decision by Friday. Could you have a look and let me know if anything is unusual?\n\nNathan",
    hasAttachment: true,
  },
];

const memos: SimMemo[] = [
  {
    id: "mo-1",
    matterId: "m-4182",
    title: "Vacant possession confirmed — 18 August 2026",
    body: "Other side confirmed by email that vacant possession will be given on settlement. Tenant vacated 2 August 2026. No lease to be handed over at settlement.",
    createdAt: "2026-08-18 3:55 PM",
    authorInitials: "SC",
  },
  {
    id: "mo-2",
    matterId: "m-4182",
    title: "Client instructions — insurance",
    body: "Client asked whether building insurance is required before settlement. Advised that risk passes to the purchaser from exchange under the standard contract and that cover should be arranged now, not at settlement. Client to confirm once policy issued.",
    createdAt: "2026-08-17 9:02 AM",
    authorInitials: "SC",
  },
  {
    id: "mo-3",
    matterId: "m-4176",
    title: "Discharge of mortgage — lodged",
    body: "Discharge authority sent to lender 11 August 2026. Lender confirmed the discharge will be ready 3 business days before settlement. Follow up 24 August 2026 if not confirmed in PEXA.",
    createdAt: "2026-08-12 2:18 PM",
    authorInitials: "SC",
  },
];

const tasks: SimTask[] = [
  {
    id: "t-1",
    matterId: "m-4182",
    name: "Confirm financier details from client",
    category: "Initial Work",
    dueOn: "2026-08-14",
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Jennie Tonner",
    priority: "High",
  },
  {
    id: "t-2",
    matterId: "m-4182",
    name: "Order council and water certificates",
    category: "Initial Work",
    dueOn: "2026-08-21",
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Jennie Tonner",
    priority: "Medium",
  },
  {
    id: "t-3",
    matterId: "m-4182",
    name: "Receive clear land tax certificate",
    category: "Pre-Settlement",
    dueOn: null,
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Jennie Tonner",
    priority: "No Priority",
  },
  {
    id: "t-4",
    matterId: "m-4176",
    name: "Prepare settlement adjustment sheet",
    category: "Pre-Settlement",
    dueOn: "2026-08-19",
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Shane Capati",
    priority: "Urgent",
  },
  {
    id: "t-5",
    matterId: "m-4176",
    name: "Confirm discharge of mortgage in PEXA",
    category: "Pre-Settlement",
    dueOn: "2026-08-24",
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Shane Capati",
    priority: "High",
  },
  {
    id: "t-6",
    matterId: "m-4190",
    name: "Send contract review report to client",
    category: "Initial Work",
    dueOn: "2026-08-20",
    completedOn: null,
    assignedTo: "Jennie Tonner",
    assignedBy: "Jennie Tonner",
    priority: "High",
  },
  {
    id: "t-7",
    matterId: "m-4193",
    name: "Send client onboarding pack",
    category: "Initial Work",
    dueOn: "2026-08-19",
    completedOn: null,
    assignedTo: "Shane Capati",
    assignedBy: "Shane Capati",
    priority: "Medium",
  },
  {
    id: "t-8",
    matterId: "m-4182",
    name: "Diarise settlement date in firm calendar",
    category: "Uncategorized",
    dueOn: "2026-08-12",
    completedOn: "2026-08-12",
    assignedTo: "Shane Capati",
    assignedBy: "Shane Capati",
    priority: "Low",
  },
];

const events: SimEvent[] = [
  {
    id: "ev-1",
    matterId: "m-4176",
    subject: "Settlement — 8/22 Kestrel Parade (PEXA)",
    location: "PEXA workspace",
    start: "2026-08-27 11:00 AM",
    end: "2026-08-27 12:00 PM",
    calendar: "Settlements",
  },
  {
    id: "ev-2",
    matterId: "m-4182",
    subject: "Settlement — 14 Marlowe Street (PEXA)",
    location: "PEXA workspace",
    start: "2026-09-04 2:00 PM",
    end: "2026-09-04 3:00 PM",
    calendar: "Settlements",
  },
  {
    id: "ev-3",
    matterId: null,
    subject: "Team file review",
    location: "Meeting room",
    start: "2026-08-20 9:00 AM",
    end: "2026-08-20 10:00 AM",
    calendar: "Shane Capati",
  },
];

const documents: SimDocument[] = [
  { id: "d-f1", matterId: "m-4182", parentId: null, name: "Post Exchange", kind: "folder", from: "", to: "", dateModified: "2026-08-18", sizeLabel: "", staffInitials: "SC" },
  { id: "d-f2", matterId: "m-4182", parentId: null, name: "Searches", kind: "folder", from: "", to: "", dateModified: "2026-08-13", sizeLabel: "", staffInitials: "SC" },
  { id: "d-f3", matterId: "m-4182", parentId: null, name: "Pre-Settlement", kind: "folder", from: "", to: "", dateModified: "2026-08-11", sizeLabel: "", staffInitials: "SC" },
  { id: "d-1", matterId: "m-4182", parentId: null, name: "Contract for Sale — 14 Marlowe Street (signed)", kind: "pdf", from: "Harrowgate Legal", to: "Cremorne Conveyancing", dateModified: "2026-08-08", sizeLabel: "3.42 MB", staffInitials: "SC" },
  { id: "d-2", matterId: "m-4182", parentId: null, name: "Section 66W Certificate", kind: "pdf", from: "Harrowgate Legal", to: "Cremorne Conveyancing", dateModified: "2026-08-08", sizeLabel: "182 KB", staffInitials: "SC" },
  { id: "d-3", matterId: "m-4182", parentId: null, name: "Client Authorisation Form — Beltran", kind: "pdf", from: "Amara Beltran", to: "Cremorne Conveyancing", dateModified: "2026-08-12", sizeLabel: "441 KB", staffInitials: "SC" },
  { id: "d-4", matterId: "m-4182", parentId: null, name: "Sewer Diagram & Drainage Search", kind: "pdf", from: "Search provider", to: "Shane Capati", dateModified: "2026-08-13", sizeLabel: "1.08 MB", staffInitials: "SC" },
  { id: "d-5", matterId: "m-4182", parentId: null, name: "Letter to client — post exchange", kind: "docx", from: "Cremorne Conveyancing", to: "Amara Beltran", dateModified: "2026-08-14", sizeLabel: "88 KB", staffInitials: "SC" },
  { id: "d-6", matterId: "m-4176", parentId: null, name: "Pre-Settlement", kind: "folder", from: "", to: "", dateModified: "2026-08-18", sizeLabel: "", staffInitials: "SC" },
  { id: "d-7", matterId: "m-4176", parentId: null, name: "Contract for Sale — 8/22 Kestrel Parade", kind: "pdf", from: "Cremorne Conveyancing", to: "Delacourt & Vine", dateModified: "2026-06-19", sizeLabel: "4.11 MB", staffInitials: "SC" },
  { id: "d-8", matterId: "m-4176", parentId: null, name: "Discharge Authority — signed", kind: "pdf", from: "Priya Raghunathan", to: "Cremorne Conveyancing", dateModified: "2026-08-11", sizeLabel: "302 KB", staffInitials: "SC" },
  { id: "d-9", matterId: "m-4190", parentId: null, name: "Contract for Sale — 61 Barrenjoey Grove (unsigned)", kind: "pdf", from: "Nathan Okonkwo", to: "Jennie Tonner", dateModified: "2026-08-16", sizeLabel: "2.75 MB", staffInitials: "JT" },
];

const timeEntries: SimTimeEntry[] = [
  {
    id: "te-1",
    matterId: "m-4182",
    date: "2026-08-08",
    staff: "Jennie Tonner",
    activityCode: "PCHS1",
    subject: "To our professional fees for acting on your purchase",
    billingMode: "Fixed",
    hours: null,
    rate: 2200,
    amountExGst: 2200,
    gst: 220,
    billable: true,
    billedInvoice: "#2681",
  },
  {
    id: "te-2",
    matterId: "m-4182",
    date: "2026-07-24",
    staff: "Jennie Tonner",
    activityCode: "REVIE",
    subject: "To our professional fees for providing a contract review",
    billingMode: "Fixed",
    hours: null,
    rate: 900,
    amountExGst: 900,
    gst: 90,
    billable: true,
    billedInvoice: "#2644",
  },
  {
    id: "te-3",
    matterId: "m-4176",
    date: "2026-08-15",
    staff: "Shane Capati",
    activityCode: "TELEP",
    subject: "Telephone attendance on client re settlement booking",
    billingMode: "Hrs",
    hours: 0.4,
    rate: 350,
    amountExGst: 140,
    gst: 14,
    billable: true,
    billedInvoice: null,
  },
  {
    id: "te-4",
    matterId: "m-4190",
    date: "2026-08-17",
    staff: "Jennie Tonner",
    activityCode: "REVIE",
    subject: "To our professional fees for providing a contract review",
    billingMode: "Fixed",
    hours: null,
    rate: 900,
    amountExGst: 900,
    gst: 90,
    billable: true,
    billedInvoice: null,
  },
];

const disbursements: SimDisbursement[] = [
  {
    id: "db-1",
    matterId: "m-4182",
    date: "2026-08-13",
    staff: "Shane Capati",
    activityCode: "SEARCH",
    subject: "Sewer diagram and drainage search",
    quantity: 1,
    price: 38.5,
    amountExGst: 35,
    gst: 3.5,
    gstInclusive: true,
    billable: true,
    billedInvoice: null,
  },
  {
    id: "db-2",
    matterId: "m-4176",
    date: "2026-08-11",
    staff: "Shane Capati",
    activityCode: "TITLE",
    subject: "Title search — 8/SP91442",
    quantity: 1,
    price: 16.2,
    amountExGst: 16.2,
    gst: 0,
    gstInclusive: false,
    billable: true,
    billedInvoice: null,
  },
];

const activities: SimActivity[] = [
  { id: "a-1", matterId: "m-4182", kind: "Email", time: "2026-08-18 3:41 PM", description: "Email received — RE: Beltran purchase from Whitlam", hours: 0.05, hasTimeEntry: false },
  { id: "a-2", matterId: "m-4182", kind: "Memo", time: "2026-08-18 3:55 PM", description: "Memo created — Vacant possession confirmed", hours: 0.1, hasTimeEntry: false },
  { id: "a-3", matterId: "m-4182", kind: "Document", time: "2026-08-14 10:12 AM", description: "Letter to client — post exchange — created", hours: 0.23, hasTimeEntry: true },
  { id: "a-4", matterId: "m-4182", kind: "Document", time: "2026-08-13 4:25 PM", description: "Sewer Diagram & Drainage Search — reviewed", hours: 0.08, hasTimeEntry: false },
  { id: "a-5", matterId: "m-4176", kind: "Email", time: "2026-08-18 11:05 AM", description: "Email received — Raghunathan sale settlement figures", hours: 0.03, hasTimeEntry: false },
  { id: "a-6", matterId: "m-4176", kind: "Matter Administration", time: "2026-08-15 9:31 AM", description: "Next step updated — Book settlement in PEXA", hours: 0.02, hasTimeEntry: false },
  { id: "a-7", matterId: "m-4190", kind: "Document", time: "2026-08-16 6:20 PM", description: "Contract for Sale — 61 Barrenjoey Grove — imported", hours: 0.05, hasTimeEntry: false },
  { id: "a-8", matterId: "m-4182", kind: "Matter Opened", time: "2026-05-11 9:00 AM", description: "Matter opened", hours: 0, hasTimeEntry: false },
];

const contacts: SimContact[] = [
  { id: "c-1", name: "Amara Beltran", type: "person", organisation: "", category: "Clients", email: "amara.beltran@examplemail.com", phone: "+61 412 908 553", address: "14 Marlowe Street, Kellyville NSW", riskAssessment: "Incomplete" },
  { id: "c-2", name: "Joel Beltran", type: "person", organisation: "", category: "Clients", email: "joel.beltran@examplemail.com", phone: "+61 412 908 554", address: "14 Marlowe Street, Kellyville NSW", riskAssessment: "Incomplete" },
  { id: "c-3", name: "Harrowgate Legal", type: "organisation", organisation: "Harrowgate Legal", category: "Solicitors", email: "info@harrowgatelegal.example", phone: "02 8835 1120", address: "Suite 4, 118 Church Street, Parramatta NSW", riskAssessment: "Complete" },
  { id: "c-4", name: "Bianca Oyelaran", type: "person", organisation: "Harrowgate Legal", category: "Solicitors", email: "bianca@harrowgatelegal.example", phone: "02 8835 1124", address: "Suite 4, 118 Church Street, Parramatta NSW", riskAssessment: "Complete" },
  { id: "c-5", name: "Priya Raghunathan", type: "person", organisation: "", category: "Clients", email: "p.raghunathan@examplemail.com", phone: "+61 438 221 070", address: "8/22 Kestrel Parade, Chatswood NSW", riskAssessment: "Complete" },
  { id: "c-6", name: "Delacourt & Vine Conveyancing", type: "organisation", organisation: "Delacourt & Vine", category: "Solicitors", email: "mail@delacourtvine.example", phone: "02 9412 6600", address: "Level 2, 9 Help Street, Chatswood NSW", riskAssessment: "Complete" },
  { id: "c-7", name: "The Hills Shire Council", type: "organisation", organisation: "The Hills Shire Council", category: "Councils", email: "council@hillsshire.example", phone: "02 9843 0555", address: "3 Columbia Court, Norwest NSW", riskAssessment: "Complete" },
  { id: "c-8", name: "Ridgeline Finance", type: "organisation", organisation: "Ridgeline Finance", category: "Mortgage Brokers", email: "brokers@ridgelinefinance.example", phone: "1300 555 210", address: "Level 8, 44 Market Street, Sydney NSW", riskAssessment: "Incomplete" },
  { id: "c-9", name: "Nathan Okonkwo", type: "person", organisation: "", category: "Clients", email: "n.okonkwo@examplemail.com", phone: "+61 401 774 316", address: "12 Alderney Way, Kellyville NSW", riskAssessment: "Incomplete" },
  { id: "c-10", name: "Sandpiper Strata Management", type: "organisation", organisation: "Sandpiper Strata", category: "Experts", email: "admin@sandpiperstrata.example", phone: "02 9007 4411", address: "Unit 3, 200 Victoria Road, Gladesville NSW", riskAssessment: "Complete" },
];

const messages: SimMessage[] = [
  {
    id: "ms-1",
    withStaff: "Jennie Tonner",
    matterId: "m-4182",
    from: "Jennie Tonner",
    body: "Shane — when you get a chance, can you chase the Beltrans for their financier details? Settlement is 4 Sept and we still have nothing on file.",
    sentAt: "2026-08-18 4:02 PM",
  },
  {
    id: "ms-2",
    withStaff: "Harold Galvo",
    matterId: null,
    from: "Harold Galvo",
    body: "Reminder: time entries for the week need to be in by Friday 3pm.",
    sentAt: "2026-08-17 8:45 AM",
  },
];

const phoneMessages: SimPhoneMessage[] = [
  {
    id: "pm-1",
    matterId: "m-4182",
    caller: "Bianca Oyelaran",
    callerPhone: "02 8835 1124",
    summary:
      "Called about the Beltran settlement figures. Asked that we confirm the incoming mortgagee before 25 August. Will email as well.",
    takenBy: "Monika Stelzner",
    forStaff: "Shane Capati",
    takenAt: "2026-08-19 9:14 AM",
  },
];

/** Documents the precedent picker can generate. */
export const PRECEDENTS = [
  "Letter to client — post exchange",
  "Letter to client — settlement confirmation",
  "Letter to other side — requisitions on title",
  "Settlement adjustment sheet",
  "Pre-settlement checklist",
  "Authority to act",
];

export const CONTACT_CATEGORIES = [
  "Clients",
  "Solicitors",
  "Councils",
  "Financial Institutions",
  "Mortgage Brokers",
  "Real Estate Agents",
  "Experts",
];

const leads: SimLead[] = [
  {
    id: "l-1",
    number: null,
    leadType: "Purchase",
    state: "NSW",
    clientName: "Tobias Renshaw",
    clientEmail: "t.renshaw@examplemail.com",
    clientPhone: "+61 402 118 774",
    otherPartyName: "Not yet known",
    propertyAddress: "9 Larkspur Way, Rouse Hill NSW 2155",
    personResponsible: "Jennie Tonner",
    referralType: "Referral — real estate agent",
    referrer: "Halloran & Pike Property",
    estimatedFee: 2200,
    notes:
      "Rang after an open home. Hasn't signed a contract yet, wants a contract review first. Agent pushing for a decision by the weekend.",
    status: "Open",
    createdAt: "2026-08-18",
    convertedMatterId: null,
  },
  {
    id: "l-2",
    number: null,
    leadType: "Sale",
    state: "NSW",
    clientName: "Georgina Pellandini",
    clientEmail: "g.pellandini@examplemail.com",
    clientPhone: "+61 439 662 015",
    otherPartyName: "Not yet known",
    propertyAddress: "112 Wattlebird Crescent, Glenhaven NSW 2156",
    personResponsible: "Shane Capati",
    referralType: "Referral — past client",
    referrer: "Wilhelmina Dagostino",
    estimatedFee: 1980,
    notes: "Listing next month. Wants a quote and an idea of what she needs to get ready.",
    status: "Open",
    createdAt: "2026-08-14",
    convertedMatterId: null,
  },
];

const workflows: SimWorkflow[] = [
  {
    id: "wf-purchase",
    name: "NSW Purchase",
    matterTypes: ["Purchase"],
    alwaysApplyToNew: true,
    tasks: [
      {
        id: "wft-1",
        name: "Open file and send client onboarding pack",
        priority: "High",
        assign: "Person Assisting",
        category: "Initial Work",
        details: "Send the retainer, cost disclosure and ID requirements.",
        hours: 0.5,
        dueRule: { kind: "days-after-open", days: 1 },
        linkedPrecedent: "Authority to act",
      },
      {
        id: "wft-2",
        name: "Complete AML/KYC verification of identity",
        priority: "Urgent",
        assign: "Person Assisting",
        category: "Initial Work",
        details: "Must be complete before any funds are accepted.",
        hours: 0.5,
        dueRule: { kind: "days-after-open", days: 3 },
        linkedPrecedent: null,
      },
      {
        id: "wft-3",
        name: "Order council, water and title searches",
        priority: "Medium",
        assign: "Person Assisting",
        category: "Initial Work",
        details: "",
        hours: 0.4,
        dueRule: { kind: "days-after-open", days: 5 },
        linkedPrecedent: null,
      },
      {
        id: "wft-4",
        name: "Confirm financier details and loan approval",
        priority: "High",
        assign: "Person Assisting",
        category: "Initial Work",
        details: "Chase the broker if the approval letter hasn't arrived.",
        hours: 0.3,
        dueRule: { kind: "days-before-settlement", days: 21 },
        linkedPrecedent: null,
      },
      {
        id: "wft-5",
        name: "Prepare settlement adjustment sheet",
        priority: "High",
        assign: "Person Assisting",
        category: "Pre-Settlement",
        details: "Rates, water and any body corporate levies.",
        hours: 1,
        dueRule: { kind: "days-before-settlement", days: 7 },
        linkedPrecedent: "Settlement adjustment sheet",
      },
      {
        id: "wft-6",
        name: "Book settlement in PEXA",
        priority: "Urgent",
        assign: "Person Responsible",
        category: "Pre-Settlement",
        details: "",
        hours: 0.3,
        dueRule: { kind: "days-before-settlement", days: 5 },
        linkedPrecedent: null,
      },
      {
        id: "wft-7",
        name: "Attend settlement",
        priority: "Urgent",
        assign: "Person Responsible",
        category: "Pre-Settlement",
        details: "",
        hours: 1,
        dueRule: { kind: "on-settlement" },
        linkedPrecedent: null,
      },
    ],
  },
  {
    id: "wf-sale",
    name: "NSW Sale",
    matterTypes: ["Sale"],
    alwaysApplyToNew: true,
    tasks: [
      {
        id: "wfs-1",
        name: "Prepare contract for sale and vendor disclosure",
        priority: "High",
        assign: "Person Responsible",
        category: "Initial Work",
        details: "Contract cannot be marketed without the prescribed documents.",
        hours: 1.5,
        dueRule: { kind: "days-after-open", days: 3 },
        linkedPrecedent: null,
      },
      {
        id: "wfs-2",
        name: "Send discharge authority to the lender",
        priority: "High",
        assign: "Person Assisting",
        category: "Pre-Settlement",
        details: "Lenders routinely take 10+ business days.",
        hours: 0.4,
        dueRule: { kind: "days-before-settlement", days: 21 },
        linkedPrecedent: null,
      },
      {
        id: "wfs-3",
        name: "Confirm discharge of mortgage in PEXA",
        priority: "Urgent",
        assign: "Person Assisting",
        category: "Pre-Settlement",
        details: "",
        hours: 0.3,
        dueRule: { kind: "days-before-settlement", days: 3 },
        linkedPrecedent: null,
      },
      {
        id: "wfs-4",
        name: "Attend settlement",
        priority: "Urgent",
        assign: "Person Responsible",
        category: "Pre-Settlement",
        details: "",
        hours: 1,
        dueRule: { kind: "on-settlement" },
        linkedPrecedent: null,
      },
    ],
  },
];

const INITIALS_TO_NAME: Record<string, string> = {
  SC: "Shane Capati",
  JT: "Jennie Tonner",
  HG: "Harold Galvo",
  MS: "Monika Stelzner",
};

function initialsToName(initials: string): string {
  return INITIALS_TO_NAME[initials] ?? initials;
}

export function createSeedState(): SimState {
  return {
    today: SIM_TODAY,
    user: SIM_USER,
    matters: matters.map((m) => ({
      ...m,
      billing: { ...m.billing },
      // Defaults derived from the data already on each seeded matter, so the
      // Matter Info fields the Create Matter wizard captures aren't blank on
      // files that existed before the trainee arrived.
      state: "NSW" as const,
      areaOfLaw: "Conveyancing" as const,
      internalReference: m.number,
      reLine: `${m.clientName} — ${m.type}`,
      matterDescription: m.propertyAddress,
      clientRole: m.type === "Sale" ? "Vendor" : "Purchaser",
      personResponsible: initialsToName(m.feeEarnerInitials),
      personAssisting: initialsToName(m.assistantInitials),
      introducer: "",
      referralType: "Existing client",
      referrer: "",
      debtor: m.clientName,
      billingType: "Fixed Fee" as const,
      feeEstimate: m.type === "Purchase" ? 2200 : 1980,
      billingUnits: "6 minute units",
      billingFrequency: "On completion",
      hourlyRate: 350,
    })),
    contacts: [...contacts],
    emails: [...emails],
    memos: [...memos],
    tasks: [...tasks],
    events: [...events],
    documents: [...documents],
    timeEntries: [...timeEntries],
    disbursements: [...disbursements],
    activities: [...activities],
    messages: [...messages],
    phoneMessages: [...phoneMessages],
    leads: leads.map((l) => ({ ...l })),
    workflows: workflows.map((w) => ({ ...w, tasks: w.tasks.map((t) => ({ ...t })) })),
    nav: {
      screen: "home",
      homeMenu: "triconvey",
      rail: "dashboard",
      matterFolder: "All",
      matterId: null,
      matterTab: "matter",
      timeSubTab: "time",
      searchQuery: "",
      leadId: null,
    },
    log: [],
  };
}
